# We deliberately don't use travis's language=python option because
# we install miniconda and use conda to get python. Additionally,
# Travis's auto-install of python doesn't work on osx images (see
# https://github.com/travis-ci/travis-ci/issues/4729).
cache:
  timeout: 300
  directories:
    - $HOME/.intake

env:
  global:
    - PYENV_VERSION=3.6

matrix:
  include:
    ########## SMOKE TESTING ##########
    - &default
      language: sh
      os: linux
      env: DESC="dev test $TRAVIS_OS_NAME"
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda;
        - export PATH="$HOME/miniconda:$HOME/miniconda/bin:$PATH";
      install:
        - hash -r;
        - echo $TRAVIS_OS_NAME
        - echo $TRAVIS_PYTHON_VERSION
        - conda config --set always_yes yes --set changeps1 no
        - conda env update python=$TRAVIS_PYTHON_VERSION -f environment.yml -n earthml
        - conda env update python=$TRAVIS_PYTHON_VERSION -f environment-dev.yml -n earthml
      before_script:
        - source activate earthml
        - doit env_capture
        - doit before_test
      script:
        - pytest --nbsmoke-run -k ".ipynb"

    - &windows
      <<: *default
      os: windows
      before_install:
        - choco install miniconda3 --params="'/AddToPath:1'";
        - export PATH="/c/tools/miniconda3/scripts:/c/tools/miniconda3/:$PATH";

    - &osx
      <<: *default
      os: osx
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda;
        - export PATH="$HOME/miniconda:$HOME/miniconda/bin:$PATH";


    ########## DOCS ##########

    - &website
      <<: *default
      if: tag =~ ^v(\d+|\.)+[^a-z]\d+$ OR tag = website
      env: DESC="website"
      before_script:
        - source activate earthml
        - doit env_capture
        - git checkout -b deploy-${TRAVIS_BRANCH}
        - git fetch https://github.com/$TRAVIS_REPO_SLUG.git evaluated:refs/remotes/evaluated # all large evaluated notebooks and their json files should be checked in to this branch
        - git checkout evaluated -- 'doc/topics/*.ipynb' 'doc/topics/*.json'  # only check in evaluated topics
      script:
        - nbsite generate-rst --org pyviz-topics --project-name earthml --offset 1 --nblink=top
        - nbsite build --what=html --output=builtdocs
        - doit move_json

      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: ./builtdocs
        fqdn: earthml.pyviz.org
        on:
          tags: true
          all_branches: true

    - <<: *website
      if: tag =~ ^v(\d+|\.)+[a-z]\d+$ OR tag = website_dev
      env: DESC="website dev"
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: ./builtdocs
        repo: pyviz-dev/earthml
        on:
          tags: true
          all_branches: true

notifications:
  email: false
